export const SET_ARTICLES = 'SET_ARTICLES';
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const PAGINATED_ARTICLES = 'PAGINATED_ARTICLES';
export const SET_SELECTED_ARTICLE = 'SET_SELECTED_ARTICLE';
